// ***********************************************************************
// Assembly         : Arp.OpcUA.UseCases.eUAClient
// Author           : 7WRMZC
// Created          : 07-01-2022
//
// Last Modified By : 7WRMZC
// Last Modified On : 06-01-2022
// ***********************************************************************
// <copyright file="UAClientIdentifiers.cs" company="Arp.OpcUA.UseCases.eUAClient">
//     Copyright (c) . All rights reserved.
// </copyright>
// <summary></summary>
// ***********************************************************************
/******************************************************************************
**
** <auto-generated>
**     This code was generated by a tool: UaModeler
**     Runtime Version: 1.6.5, using .NET Client 3.0.0 template (version 2)
**
**     Changes to this file may cause incorrect behavior and will be lost if
**     the code is regenerated.
**
** </auto-generated>
**
** Copyright (c) 2006-2022 Unified Automation GmbH All rights reserved.
**
** Software License Agreement ("SLA") Version 2.7
**
** Unless explicitly acquired and licensed from Licensor under another
** license, the contents of this file are subject to the Software License
** Agreement ("SLA") Version 2.7, or subsequent versions
** as allowed by the SLA, and You may not copy or use this file in either
** source code or executable form, except in compliance with the terms and
** conditions of the SLA.
**
** All software distributed under the SLA is provided strictly on an
** "AS IS" basis, WITHOUT WARRANTY OF ANY KIND, EITHER EXPRESS OR IMPLIED,
** AND LICENSOR HEREBY DISCLAIMS ALL SUCH WARRANTIES, INCLUDING WITHOUT
** LIMITATION, ANY WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR
** PURPOSE, QUIET ENJOYMENT, OR NON-INFRINGEMENT. See the SLA for specific
** language governing rights and limitations under the SLA.
**
** Project: .NET OPC UA SDK information model for namespace http://yourorganisation.org/UAClientConfig/
**
** Description: OPC Unified Architecture Software Development Kit.
**
** The complete license agreement can be found here:
** http://unifiedautomation.com/License/SLA/2.7/
**
******************************************************************************/

using System;
using System.Collections.Generic;
using System.Text;
using System.Reflection;
using System.Xml;
using System.Runtime.Serialization;
using Opc.Ua;

namespace Arp.OpcUA.ClientConfiguration
{
    #region DataType Identifiers
    /// <summary>
    /// A class that declares constants for all DataTypes in the Model.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("UaModeler", "1.6.5")]
    public static partial class DataTypes
    {
        /// <summary>
        /// The identifier for the eUAClientGroupType DataType.
        /// </summary>
        public const uint eUAClientGroupType = 3007;

        /// <summary>
        /// The identifier for the eUAClientConfiguration DataType.
        /// </summary>
        public const uint eUAClientConfiguration = 3003;

        /// <summary>
        /// The identifier for the eUAClientNodeMapping DataType.
        /// </summary>
        public const uint eUAClientNodeMapping = 3005;

        /// <summary>
        /// The identifier for the eUAClientRemoteVariableDescriptor DataType.
        /// </summary>
        public const uint eUAClientRemoteVariableDescriptor = 3006;

        /// <summary>
        /// The identifier for the eUAClientServerConnection DataType.
        /// </summary>
        public const uint eUAClientServerConnection = 3002;

        /// <summary>
        /// The identifier for the eUAClientVariableGroup DataType.
        /// </summary>
        public const uint eUAClientVariableGroup = 3004;

    }
    #endregion

    #region Object Identifiers
    /// <summary>
    /// A class that declares constants for all Objects in the Model.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("UaModeler", "1.6.5")]
    public static partial class Objects
    {
        /// <summary>
        /// The identifier for the Default Binary Object.
        /// </summary>
        public const uint eUAClientConfiguration_Encoding_DefaultBinary = 5004;

        /// <summary>
        /// The identifier for the Default JSON Object.
        /// </summary>
        public const uint eUAClientConfiguration_Encoding_DefaultJson = 5006;

        /// <summary>
        /// The identifier for the Default XML Object.
        /// </summary>
        public const uint eUAClientConfiguration_Encoding_DefaultXml = 5005;

        /// <summary>
        /// The identifier for the Default Binary Object.
        /// </summary>
        public const uint eUAClientNodeMapping_Encoding_DefaultBinary = 5010;

        /// <summary>
        /// The identifier for the Default JSON Object.
        /// </summary>
        public const uint eUAClientNodeMapping_Encoding_DefaultJson = 5012;

        /// <summary>
        /// The identifier for the Default XML Object.
        /// </summary>
        public const uint eUAClientNodeMapping_Encoding_DefaultXml = 5011;

        /// <summary>
        /// The identifier for the Default Binary Object.
        /// </summary>
        public const uint eUAClientRemoteVariableDescriptor_Encoding_DefaultBinary = 5013;

        /// <summary>
        /// The identifier for the Default JSON Object.
        /// </summary>
        public const uint eUAClientRemoteVariableDescriptor_Encoding_DefaultJson = 5015;

        /// <summary>
        /// The identifier for the Default XML Object.
        /// </summary>
        public const uint eUAClientRemoteVariableDescriptor_Encoding_DefaultXml = 5014;

        /// <summary>
        /// The identifier for the Default Binary Object.
        /// </summary>
        public const uint eUAClientServerConnection_Encoding_DefaultBinary = 5001;

        /// <summary>
        /// The identifier for the Default JSON Object.
        /// </summary>
        public const uint eUAClientServerConnection_Encoding_DefaultJson = 5003;

        /// <summary>
        /// The identifier for the Default XML Object.
        /// </summary>
        public const uint eUAClientServerConnection_Encoding_DefaultXml = 5002;

        /// <summary>
        /// The identifier for the Default Binary Object.
        /// </summary>
        public const uint eUAClientVariableGroup_Encoding_DefaultBinary = 5007;

        /// <summary>
        /// The identifier for the Default JSON Object.
        /// </summary>
        public const uint eUAClientVariableGroup_Encoding_DefaultJson = 5009;

        /// <summary>
        /// The identifier for the Default XML Object.
        /// </summary>
        public const uint eUAClientVariableGroup_Encoding_DefaultXml = 5008;

    }
    #endregion

    #region ObjectType Identifiers
    /// <summary>
    /// A class that declares constants for all ObjectTypes in the Model.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("UaModeler", "1.6.5")]
    public static partial class ObjectTypes
    {
    }
    #endregion

    #region Method Identifiers
    /// <summary>
    /// A class that declares constants for all Methods in the Model.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("UaModeler", "1.6.5")]
    public static partial class Methods
    {
    }
    #endregion

    #region ReferenceType Identifiers
    /// <summary>
    /// A class that declares constants for all ReferenceTyped in the Model.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("UaModeler", "1.6.5")]
    public static partial class ReferenceTypes
    {
    }
    #endregion

    #region Variable Identifiers
    /// <summary>
    /// A class that declares constants for all Variables in the Model.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("UaModeler", "1.6.5")]
    public static partial class Variables
    {
        /// <summary>
        /// The identifier for the EnumStrings Variable.
        /// </summary>
        public const uint eUAClientGroupType_EnumStrings = 6001;

    }
    #endregion

    #region VariableTypes Identifiers
    /// <summary>
    /// A class that declares constants for all VariableTypes in the Model.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("UaModeler", "1.6.5")]
    public static partial class VariableTypes
    {
    }
    #endregion

    #region DataType Node Identifiers
    /// <summary>
    /// A class that declares ExpandedNodeIds for all DataTypes in the Model.
    /// </summary>
    /// <remarks>Call ExpandedNodeId.ToNodeId to use these constants.</remarks>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("UaModeler", "1.6.5")]
    public static partial class DataTypeIds
    {
        /// <summary>
        /// The identifier for the BaseDataType DataType.
        /// </summary>
        public static readonly ExpandedNodeId eUAClientGroupType = new ExpandedNodeId(DataTypes.eUAClientGroupType, Namespaces.UAClient);

        /// <summary>
        /// The identifier for the BaseDataType DataType.
        /// </summary>
        public static readonly ExpandedNodeId eUAClientConfiguration = new ExpandedNodeId(DataTypes.eUAClientConfiguration, Namespaces.UAClient);

        /// <summary>
        /// The identifier for the BaseDataType DataType.
        /// </summary>
        public static readonly ExpandedNodeId eUAClientNodeMapping = new ExpandedNodeId(DataTypes.eUAClientNodeMapping, Namespaces.UAClient);

        /// <summary>
        /// The identifier for the BaseDataType DataType.
        /// </summary>
        public static readonly ExpandedNodeId eUAClientRemoteVariableDescriptor = new ExpandedNodeId(DataTypes.eUAClientRemoteVariableDescriptor, Namespaces.UAClient);

        /// <summary>
        /// The identifier for the BaseDataType DataType.
        /// </summary>
        public static readonly ExpandedNodeId eUAClientServerConnection = new ExpandedNodeId(DataTypes.eUAClientServerConnection, Namespaces.UAClient);

        /// <summary>
        /// The identifier for the BaseDataType DataType.
        /// </summary>
        public static readonly ExpandedNodeId eUAClientVariableGroup = new ExpandedNodeId(DataTypes.eUAClientVariableGroup, Namespaces.UAClient);

    }
    #endregion

    #region Method Node Identifiers
    /// <summary>
    /// A class that declares ExpandedNodeIds for all Methods in the Model.
    /// </summary>
    /// <remarks>Call ExpandedNodeId.ToNodeId to use these constants.</remarks>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("UaModeler", "1.6.5")]
    public static partial class MethodIds
    {
    }
    #endregion

    #region Object Node Identifiers
    /// <summary>
    /// A class that declares ExpandedNodeIds for all Objects in the Model.
    /// </summary>
    /// <remarks>Call ExpandedNodeId.ToNodeId to use these constants.</remarks>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("UaModeler", "1.6.5")]
    public static partial class ObjectIds
    {
        /// <summary>
        /// The identifier for the eUAClientConfiguration_Encoding_DefaultBinary Object.
        /// </summary>
        public static readonly ExpandedNodeId eUAClientConfiguration_Encoding_DefaultBinary = new ExpandedNodeId(Objects.eUAClientConfiguration_Encoding_DefaultBinary, Namespaces.UAClient);

        /// <summary>
        /// The identifier for the eUAClientConfiguration_Encoding_DefaultJson Object.
        /// </summary>
        public static readonly ExpandedNodeId eUAClientConfiguration_Encoding_DefaultJson = new ExpandedNodeId(Objects.eUAClientConfiguration_Encoding_DefaultJson, Namespaces.UAClient);

        /// <summary>
        /// The identifier for the eUAClientConfiguration_Encoding_DefaultXml Object.
        /// </summary>
        public static readonly ExpandedNodeId eUAClientConfiguration_Encoding_DefaultXml = new ExpandedNodeId(Objects.eUAClientConfiguration_Encoding_DefaultXml, Namespaces.UAClient);

        /// <summary>
        /// The identifier for the eUAClientNodeMapping_Encoding_DefaultBinary Object.
        /// </summary>
        public static readonly ExpandedNodeId eUAClientNodeMapping_Encoding_DefaultBinary = new ExpandedNodeId(Objects.eUAClientNodeMapping_Encoding_DefaultBinary, Namespaces.UAClient);

        /// <summary>
        /// The identifier for the eUAClientNodeMapping_Encoding_DefaultJson Object.
        /// </summary>
        public static readonly ExpandedNodeId eUAClientNodeMapping_Encoding_DefaultJson = new ExpandedNodeId(Objects.eUAClientNodeMapping_Encoding_DefaultJson, Namespaces.UAClient);

        /// <summary>
        /// The identifier for the eUAClientNodeMapping_Encoding_DefaultXml Object.
        /// </summary>
        public static readonly ExpandedNodeId eUAClientNodeMapping_Encoding_DefaultXml = new ExpandedNodeId(Objects.eUAClientNodeMapping_Encoding_DefaultXml, Namespaces.UAClient);

        /// <summary>
        /// The identifier for the eUAClientRemoteVariableDescriptor_Encoding_DefaultBinary Object.
        /// </summary>
        public static readonly ExpandedNodeId eUAClientRemoteVariableDescriptor_Encoding_DefaultBinary = new ExpandedNodeId(Objects.eUAClientRemoteVariableDescriptor_Encoding_DefaultBinary, Namespaces.UAClient);

        /// <summary>
        /// The identifier for the eUAClientRemoteVariableDescriptor_Encoding_DefaultJson Object.
        /// </summary>
        public static readonly ExpandedNodeId eUAClientRemoteVariableDescriptor_Encoding_DefaultJson = new ExpandedNodeId(Objects.eUAClientRemoteVariableDescriptor_Encoding_DefaultJson, Namespaces.UAClient);

        /// <summary>
        /// The identifier for the eUAClientRemoteVariableDescriptor_Encoding_DefaultXml Object.
        /// </summary>
        public static readonly ExpandedNodeId eUAClientRemoteVariableDescriptor_Encoding_DefaultXml = new ExpandedNodeId(Objects.eUAClientRemoteVariableDescriptor_Encoding_DefaultXml, Namespaces.UAClient);

        /// <summary>
        /// The identifier for the eUAClientServerConnection_Encoding_DefaultBinary Object.
        /// </summary>
        public static readonly ExpandedNodeId eUAClientServerConnection_Encoding_DefaultBinary = new ExpandedNodeId(Objects.eUAClientServerConnection_Encoding_DefaultBinary, Namespaces.UAClient);

        /// <summary>
        /// The identifier for the eUAClientServerConnection_Encoding_DefaultJson Object.
        /// </summary>
        public static readonly ExpandedNodeId eUAClientServerConnection_Encoding_DefaultJson = new ExpandedNodeId(Objects.eUAClientServerConnection_Encoding_DefaultJson, Namespaces.UAClient);

        /// <summary>
        /// The identifier for the eUAClientServerConnection_Encoding_DefaultXml Object.
        /// </summary>
        public static readonly ExpandedNodeId eUAClientServerConnection_Encoding_DefaultXml = new ExpandedNodeId(Objects.eUAClientServerConnection_Encoding_DefaultXml, Namespaces.UAClient);

        /// <summary>
        /// The identifier for the eUAClientVariableGroup_Encoding_DefaultBinary Object.
        /// </summary>
        public static readonly ExpandedNodeId eUAClientVariableGroup_Encoding_DefaultBinary = new ExpandedNodeId(Objects.eUAClientVariableGroup_Encoding_DefaultBinary, Namespaces.UAClient);

        /// <summary>
        /// The identifier for the eUAClientVariableGroup_Encoding_DefaultJson Object.
        /// </summary>
        public static readonly ExpandedNodeId eUAClientVariableGroup_Encoding_DefaultJson = new ExpandedNodeId(Objects.eUAClientVariableGroup_Encoding_DefaultJson, Namespaces.UAClient);

        /// <summary>
        /// The identifier for the eUAClientVariableGroup_Encoding_DefaultXml Object.
        /// </summary>
        public static readonly ExpandedNodeId eUAClientVariableGroup_Encoding_DefaultXml = new ExpandedNodeId(Objects.eUAClientVariableGroup_Encoding_DefaultXml, Namespaces.UAClient);

    }
    #endregion

    #region ObjectType Node Identifiers
    /// <summary>
    /// A class that declares ExpandedNodeIds for all Objects in the Model.
    /// </summary>
    /// <remarks>Call ExpandedNodeId.ToNodeId to use these constants.</remarks>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("UaModeler", "1.6.5")]
    public static partial class ObjectTypeIds
    {
    }
    #endregion

    #region ReferenceType Node Identifiers
    /// <summary>
    /// A class that declares ExpandedNodeIds for all ReferenceTypes in the Model.
    /// </summary>
    /// <remarks>Call ExpandedNodeId.ToNodeId to use these constants.</remarks>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("UaModeler", "1.6.5")]
    public static partial class ReferenceTypeIds
    {
    }
    #endregion

    #region Variable Node Identifiers
    /// <summary>
    /// A class that declares ExpandedNodeIds for all Variables in the Model.
    /// </summary>
    /// <remarks>Call ExpandedNodeId.ToNodeId to use these constants.</remarks>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("UaModeler", "1.6.5")]
    public static partial class VariableIds
    {
        /// <summary>
        /// The identifier for the eUAClientGroupType_EnumStrings Variable.
        /// </summary>
        public static readonly ExpandedNodeId eUAClientGroupType_EnumStrings = new ExpandedNodeId(Variables.eUAClientGroupType_EnumStrings, Namespaces.UAClient);

    }
    #endregion

    #region VariableType Node Identifiers
    /// <summary>
    /// A class that declares ExpandedNodeIds for all VariableType in the Model.
    /// </summary>
    /// <remarks>Call ExpandedNodeId.ToNodeId to use these constants.</remarks>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("UaModeler", "1.6.5")]
    public static partial class VariableTypeIds
    {
    }
    #endregion

    #region BrowseName Declarations
    /// <summary>
    /// Declares all of the BrowseNames used in the Model.
    /// </summary>
    public static partial class BrowseNames
    {
        /// <summary>
        /// The BrowseName for the eUAClientConfiguration component.
        /// </summary>
        public const string eUAClientConfiguration = "eUAClientConfiguration";
        /// <summary>
        /// The BrowseName for the eUAClientGroupType component.
        /// </summary>
        public const string eUAClientGroupType = "eUAClientGroupType";
        /// <summary>
        /// The BrowseName for the eUAClientNodeMapping component.
        /// </summary>
        public const string eUAClientNodeMapping = "eUAClientNodeMapping";
        /// <summary>
        /// The BrowseName for the eUAClientRemoteVariableDescriptor component.
        /// </summary>
        public const string eUAClientRemoteVariableDescriptor = "eUAClientRemoteVariableDescriptor";
        /// <summary>
        /// The BrowseName for the eUAClientServerConnection component.
        /// </summary>
        public const string eUAClientServerConnection = "eUAClientServerConnection";
        /// <summary>
        /// The BrowseName for the eUAClientVariableGroup component.
        /// </summary>
        public const string eUAClientVariableGroup = "eUAClientVariableGroup";
    }
    #endregion

    #region Namespace Declarations
    /// <summary>
    /// Defines constants for all namespaces referenced by the Model.
    /// </summary>
    public static partial class Namespaces
    {
        /// <summary>
        /// The URI for the OpcUa namespace (.NET code namespace is 'Opc.Ua').
        /// </summary>
        public const string OpcUa = "http://opcfoundation.org/UA/";

        /// <summary>
        /// The URI for the OpcUaXsd namespace (.NET code namespace is 'Opc.Ua').
        /// </summary>
        public const string OpcUaXsd = "http://opcfoundation.org/UA/2008/02/Types.xsd";

        /// <summary>
        /// The URI for the UAClient namespace.
        /// </summary>
        public const string UAClient = "http://phoenixcontact.com/OpcUA/PLCnext/UAClientConfig/";

        /// <summary>
        /// The URI for the UAClientXsd namespace.
        /// </summary>
        public const string UAClientXsd = "http://phoenixcontact.com/OpcUA/PLCnext/UAClientConfig/Types.xsd";
    }
    #endregion
}

